### ISSUE TITLE
Update AMP managed collector authentication mechanism 

### ISSUE THREAD

**Issue by vickywh** [aws-samples/terraform-workloads-ready-eks-accelerator#9] opened 2024-05-16 11:04 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The newly released feature for the AMP managed collectors removes the need to add entries to the AWS auth-config map, instead using the cluster access management APIs. We should update our implementation to reflect this. 

**Describe alternatives you've considered**
N/A

**Additional context**
Announcement here: https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-managed-service-prometheus-collector-eks-access-management-controls/

**Comment by tsahiduek** [comment] 2024-06-10 15:27
duplicate of #8

**Closed by tsahiduek** 2024-06-10 15:27 UTC
